apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: production
    app: flask-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "gitops-notifications"

spec:
  project: default

  source:
    repoURL: https://github.com/Mfarajpour/flask-gitops-app.git
    targetRevision: main
    path: k8s/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app-prod

  syncPolicy:
    # ← Manual sync! automated حذف شده
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 1m
        factor: 2
