apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: staging
    app: flask-gitops

spec:
  project: default

  source:
    repoURL: https://github.com/Mfarajpour/flask-gitops-app.git
    targetRevision: main
    path: k8s/overlays/staging 

  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true

    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 1m
        factor: 2
